{% set name = "allure-python" %}
{% set version = "2.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/allure-framework/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 17af5ba84834015f6f0f0929277aa41d0a9760c9ed29b0506f3810f7fe23bb30

build:
  number: 0
  skip: True  # [py<38]

outputs:
  - name: allure-python-commons
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
        - setuptools-scm
      run:
        - python
        - attrs >=16.0.0
        - pluggy >=0.4.0
    test:
      imports:
        - allure
        - allure_commons

  - name: allure-python-commons-test
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
        - setuptools-scm
      run:
        - python
        - pyhamcrest >=1.9.0
    test:
      imports:
        - allure_commons_test

  - name: allure-behave
    build:
      # The behave pkg for py313 is not available, and it is impossible to release behave for py313,
      # as it needs setuptools 52.0.0 with version py313 and distutils required inside.
      # The distutils is deprecated in Python > 3.11
      skip: True  # [py>311]
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
        - setuptools-scm
      run:
        - python
        - behave >=1.2.5
        - {{ pin_subpackage('allure-python-commons', exact=True) }}
    test:
      source_files:
        - allure-behave/examples/*
        - tests/conftest.py
        - tests/e2e.py
        - tests/__init__.py
        - tests/allure_behave
      imports:
        - allure_behave
      commands:
        - pytest -v tests/allure_behave
      requires:
        - {{ pin_subpackage('allure-python-commons-test', exact=True) }}
        - pytest
        - docutils
        - mock
        - packaging
        - pyhamcrest
        - pygments

  - name: allure-nose2
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
        - setuptools-scm
      run:
        - python
        - nose2
        - {{ pin_subpackage('allure-python-commons', exact=True) }}
    test:
      source_files:
        - tests/conftest.py
        - tests/e2e.py
        - tests/__init__.py
        - tests/allure_nose2
      imports:
        - allure_nose2
      commands:
        - pytest -v tests/allure_nose2
      requires:
        - {{ pin_subpackage('allure-python-commons-test', exact=True) }}
        - pytest
        - docutils
        - mock
        - packaging
        - pyhamcrest
        - pygments

  - name: allure-pytest
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
        - setuptools-scm
      run:
        - python
        - pytest >=4.5.0
        - {{ pin_subpackage('allure-python-commons', exact=True) }}
    test:
      source_files:
        - allure-pytest/examples/*
        - tests/conftest.py
        - tests/e2e.py
        - tests/__init__.py
        - tests/allure_pytest
      imports:
        - allure_pytest
      commands:
        # ImportError: Error importing plugin "check": No module named 'check'
        # Needs pytest-check, which is not available in the main channel.
        - pytest -v -k "not test_pytest_check" tests/allure_pytest  # [not win]
        # AssertionError: Expected greater 1745831725925, but 1745831725859.
        - pytest -v -k "not test_pytest_check or test_duration" tests/allure_pytest  # [win]
      requires:
        - {{ pin_subpackage('allure-python-commons-test', exact=True) }}
        - pytest
        - pytest-xdist
        - pytest-rerunfailures
        - pytest-flakes
        - docutils
        - mock
        - packaging
        - pyhamcrest
        - pygments

  - name: allure-pytest-bdd
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
        - setuptools-scm
      run:
        - python
        - pytest >=4.5.0
        - pytest-bdd >=5.0.0
        - {{ pin_subpackage('allure-python-commons', exact=True) }}
    test:
      source_files:
        - tests/conftest.py
        - tests/e2e.py
        - tests/__init__.py
        - tests/allure_pytest_bdd
        - tests/allure_pytest
      imports:
        - allure_pytest_bdd
      commands:
        - pytest -v tests/allure_pytest_bdd --clean-alluredir
      requires:
        - {{ pin_subpackage('allure-python-commons-test', exact=True) }}
        - pytest <8.0
        - pytest-bdd <8.0
        - docutils
        - mock
        - packaging
        - pyhamcrest
        - pygments

  - name: allure-robotframework
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      host:
        - pip
        - python 
        - setuptools
        - wheel
        - setuptools-scm
      run:
        - python
        - robotframework
        - {{ pin_subpackage('allure-python-commons', exact=True) }}
    test:
      source_files:
        - allure-robotframework/examples/*
        - tests/conftest.py
        - tests/e2e.py
        - tests/__init__.py
        - tests/allure_robotframework
      imports:
        - AllureLibrary
        - allure_robotframework
      commands:
        - pytest -v tests/allure_robotframework
      requires:
        - {{ pin_subpackage('allure-python-commons-test', exact=True) }}
        - pytest
        - docutils
        - mock
        - packaging
        - pyhamcrest
        - pygments

about:
  home: https://github.com/allure-framework/allure-python
  dev_url: https://github.com/allure-framework/allure-python
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Allure integrations for Python test frameworks
  description: |
    Allure Framework is a flexible lightweight multi-language test report tool that not only shows a very concise representation of what have been tested in a neat web report form, but allows everyone participating in the development process to extract maximum of useful information from everyday execution of tests.
  doc_url: https://allurereport.org/docs/
  
extra:
  recipe-maintainers:
    - kenodegard
    - nsoranzo
